# Generated by Django 4.1.7 on 2023-02-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SSLHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SSL_ID", models.UUIDField()),
                ("date_earned", models.DateField()),
                ("project_name", models.CharField(max_length=255)),
                ("hours", models.DecimalField(decimal_places=1, max_digits=4)),
                ("username", models.CharField(max_length=255)),
                ("student_id", models.CharField(max_length=10)),
                ("school_name", models.CharField(max_length=255)),
                ("club", models.CharField(max_length=255)),
                ("dt_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
